azure:
  subscription_id: [your subscription id]
  tenant_id: [your tenant id]
  client_id: [your client id]
  client_secret: [you client secret]
  deployment:
    location: chinaeast2

project:
  name: icduser02 # length must within 10
  admin:
    username: iotadmin
    password: [your password]